#!/usr/bin/env python3
"""Offline trainer for Bladelow's local JSONL datasets.

This script reads the learning datasets generated by the mod and produces a
lightweight `offline_model.json` file with zone/theme priors. The runtime can
load those priors directly without any heavy ML dependencies.
"""

from __future__ import annotations

import argparse
import collections
import json
import math
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List


@dataclass
class GroupSummary:
    samples: int
    archetype: str
    size_class: str
    floors: int
    roof_family: str
    palette_profile: str
    detail_density: str
    primary_theme: str
    secondary_theme: str
    confidence: float


def normalize(text: str | None) -> str:
    if text is None:
        return ""
    return str(text).strip().lower()


def read_jsonl(path: Path) -> List[dict]:
    if not path.exists():
        return []
    rows: List[dict] = []
    with path.open("r", encoding="utf-8") as handle:
        for raw in handle:
            raw = raw.strip()
            if not raw:
                continue
            try:
                rows.append(json.loads(raw))
            except json.JSONDecodeError:
                continue
    return rows


def count_images(path: Path) -> int:
    if not path.exists():
        return 0
    return sum(1 for file in path.iterdir() if file.is_file() and file.suffix.lower() in {".png", ".jpg", ".jpeg"})


def weighted_theme_counts(environment_rows: Iterable[dict], style_rows: Iterable[dict]) -> collections.Counter[str]:
    counts: collections.Counter[str] = collections.Counter()
    for row in environment_rows:
        counts[normalize(row.get("primaryTheme"))] += 2
        counts[normalize(row.get("secondaryTheme"))] += 1
    for row in style_rows:
        counts[normalize(row.get("primaryTheme"))] += 6
        counts[normalize(row.get("secondaryTheme"))] += 3
        counts[normalize(row.get("label"))] += 2
    counts.pop("", None)
    return counts


def build_group_summary(rows: List[dict]) -> GroupSummary | None:
    if not rows:
        return None

    samples = len(rows)
    archetypes = collections.Counter(normalize(row.get("archetype")) for row in rows if normalize(row.get("archetype")))
    size_classes = collections.Counter(normalize(row.get("sizeClass")) for row in rows if normalize(row.get("sizeClass")))
    roofs = collections.Counter(normalize(row.get("roofFamily")) for row in rows if normalize(row.get("roofFamily")))
    palettes = collections.Counter(normalize(row.get("paletteProfile")) for row in rows if normalize(row.get("paletteProfile")))
    details = collections.Counter(normalize(row.get("detailDensity")) for row in rows if normalize(row.get("detailDensity")))
    primary_themes = collections.Counter()
    secondary_themes = collections.Counter()
    floors: List[int] = []

    for row in rows:
        learned_primary = normalize(row.get("learnedPrimaryTheme"))
        style_primary = normalize(row.get("stylePrimaryTheme"))
        learned_secondary = normalize(row.get("learnedSecondaryTheme"))
        style_secondary = normalize(row.get("styleSecondaryTheme"))

        primary = learned_primary or style_primary
        secondary = learned_secondary or style_secondary
        if primary:
            primary_themes[primary] += 1
        if secondary and secondary != primary:
            secondary_themes[secondary] += 1

        try:
            floors.append(int(row.get("floors", 1)))
        except (TypeError, ValueError):
            floors.append(1)

    archetype, archetype_hits = most_common(archetypes)
    palette, palette_hits = most_common(palettes)
    roof, roof_hits = most_common(roofs)
    size_class, size_hits = most_common(size_classes)
    detail, detail_hits = most_common(details)
    primary_theme, _ = most_common(primary_themes)
    secondary_theme, _ = most_common(secondary_themes)
    mean_floors = max(1, int(round(sum(floors) / max(1, len(floors)))))

    purity_terms = [
        safe_ratio(archetype_hits, samples),
        safe_ratio(palette_hits, samples),
        safe_ratio(roof_hits, samples),
        safe_ratio(size_hits, samples),
        safe_ratio(detail_hits, samples),
    ]
    purity = sum(purity_terms) / len(purity_terms)
    confidence = min(0.95, 0.35 + purity * 0.40 + min(1.0, samples / 12.0) * 0.20)

    return GroupSummary(
        samples=samples,
        archetype=archetype,
        size_class=size_class,
        floors=mean_floors,
        roof_family=roof,
        palette_profile=palette,
        detail_density=detail,
        primary_theme=primary_theme,
        secondary_theme=secondary_theme,
        confidence=round(confidence, 4),
    )


def most_common(counter: collections.Counter[str]) -> tuple[str, int]:
    if not counter:
        return "", 0
    return counter.most_common(1)[0]


def safe_ratio(numerator: int, denominator: int) -> float:
    if denominator <= 0:
        return 0.0
    return numerator / float(denominator)


def encode_summary(summary: GroupSummary) -> dict:
    return {
        "archetype": summary.archetype,
        "sizeClass": summary.size_class,
        "floors": summary.floors,
        "roofFamily": summary.roof_family,
        "paletteProfile": summary.palette_profile,
        "detailDensity": summary.detail_density,
        "primaryTheme": summary.primary_theme,
        "secondaryTheme": summary.secondary_theme,
        "confidence": summary.confidence,
        "samples": summary.samples,
    }


def top_named_counts(counter: collections.Counter[str], limit: int) -> List[dict]:
    out: List[dict] = []
    for name, count in counter.most_common(limit):
        if not name:
            continue
        out.append({"name": name, "count": count})
    return out


def build_zone_priors(intent_rows: List[dict]) -> Dict[str, dict]:
    grouped: Dict[str, List[dict]] = collections.defaultdict(list)
    for row in intent_rows:
        zone = normalize(row.get("zoneType"))
        if zone:
            grouped[zone].append(row)

    priors: Dict[str, dict] = {}
    for zone, rows in grouped.items():
        summary = build_group_summary(rows)
        if summary is not None:
            priors[zone] = encode_summary(summary)
    return priors


def build_theme_priors(intent_rows: List[dict]) -> Dict[str, dict]:
    grouped: Dict[str, List[dict]] = collections.defaultdict(list)
    for row in intent_rows:
        learned = normalize(row.get("learnedPrimaryTheme"))
        style = normalize(row.get("stylePrimaryTheme"))
        theme = learned or style
        if theme:
            grouped[theme].append(row)

    priors: Dict[str, dict] = {}
    for theme, rows in grouped.items():
        summary = build_group_summary(rows)
        if summary is not None:
            priors[theme] = encode_summary(summary)
    return priors


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train Bladelow offline priors from JSONL datasets.")
    parser.add_argument(
        "--ml-dir",
        default="config/bladelow/ml",
        help="Directory containing placement_style_events.jsonl and related datasets.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Optional output path. Defaults to <ml-dir>/offline_model.json",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    ml_dir = Path(args.ml_dir)
    output_path = Path(args.output) if args.output else ml_dir / "offline_model.json"
    ml_dir.mkdir(parents=True, exist_ok=True)

    placement_rows = read_jsonl(ml_dir / "placement_style_events.jsonl")
    environment_rows = read_jsonl(ml_dir / "environment_observations.jsonl")
    intent_rows = read_jsonl(ml_dir / "build_intent_examples.jsonl")
    style_example_rows = read_jsonl(ml_dir / "style_examples.jsonl")

    theme_counts = weighted_theme_counts(environment_rows, style_example_rows)
    palette_counts = collections.Counter(
        normalize(row.get("paletteProfile"))
        for row in intent_rows
        if normalize(row.get("paletteProfile"))
    )

    model = {
        "version": 1,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "sampleCounts": {
            "placementEvents": len(placement_rows),
            "environmentObservations": len(environment_rows),
            "buildIntentExamples": len(intent_rows),
            "styleExamples": len(style_example_rows),
            "styleReferenceImages": count_images(ml_dir / "style_refs"),
        },
        "topThemes": top_named_counts(theme_counts, 6),
        "topPalettes": top_named_counts(palette_counts, 6),
        "zonePriors": build_zone_priors(intent_rows),
        "themePriors": build_theme_priors(intent_rows),
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        json.dump(model, handle, indent=2, sort_keys=True)
        handle.write("\n")

    print(f"trained offline model -> {output_path}")
    print(
        "samples:",
        f"placements={len(placement_rows)}",
        f"env={len(environment_rows)}",
        f"intent={len(intent_rows)}",
        f"style_examples={len(style_example_rows)}",
    )
    if model["topThemes"]:
        print("top themes:", ", ".join(f"{entry['name']}({entry['count']})" for entry in model["topThemes"]))
    if model["zonePriors"]:
        print("zone priors:", ", ".join(sorted(model["zonePriors"].keys())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
