#!/usr/bin/env python3
"""Offline trainer for Bladelow's local JSONL datasets.

This script reads the learning datasets generated by the mod and produces a
lightweight `offline_model.json` file with zone/theme priors and a logistic
preference model for procedural geometry. The runtime can load those values
directly without any heavy ML dependencies.
"""

from __future__ import annotations

import argparse
import collections
import json
import math
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Sequence


GENERATION_FEATURES = (
    "widthFill",
    "depthFill",
    "areaFill",
    "compactness",
    "floors",
    "roofFill",
)
MIN_GENERATION_SAMPLES = 8


@dataclass
class GroupSummary:
    samples: int
    archetype: str
    size_class: str
    floors: int
    roof_family: str
    palette_profile: str
    detail_density: str
    primary_theme: str
    secondary_theme: str
    confidence: float


def normalize(text: str | None) -> str:
    if text is None:
        return ""
    return str(text).strip().lower()


def read_jsonl(path: Path) -> List[dict]:
    if not path.exists():
        return []
    rows: List[dict] = []
    skipped = 0
    with path.open("r", encoding="utf-8") as handle:
        for line_num, raw in enumerate(handle, start=1):
            raw = raw.strip()
            if not raw:
                continue
            try:
                rows.append(json.loads(raw))
            except json.JSONDecodeError as exc:
                skipped += 1
                print(f"  warning: {path.name}:{line_num} skipped — {exc}", file=sys.stderr)
    if skipped:
        print(f"  warning: {path.name} skipped {skipped} malformed line(s) out of {len(rows) + skipped} total", file=sys.stderr)
    return rows


def count_images(path: Path) -> int:
    if not path.exists():
        return 0
    return sum(1 for file in path.iterdir() if file.is_file() and file.suffix.lower() in {".png", ".jpg", ".jpeg"})


def weighted_theme_counts(environment_rows: Iterable[dict], style_rows: Iterable[dict]) -> collections.Counter[str]:
    counts: collections.Counter[str] = collections.Counter()
    for row in environment_rows:
        counts[normalize(row.get("primaryTheme"))] += 2
        counts[normalize(row.get("secondaryTheme"))] += 1
    for row in style_rows:
        counts[normalize(row.get("primaryTheme"))] += 6
        counts[normalize(row.get("secondaryTheme"))] += 3
        counts[normalize(row.get("label"))] += 2
    counts.pop("", None)
    return counts


def build_group_summary(rows: List[dict]) -> GroupSummary | None:
    if not rows:
        return None

    samples = len(rows)
    archetypes = collections.Counter(normalize(row.get("archetype")) for row in rows if normalize(row.get("archetype")))
    size_classes = collections.Counter(normalize(row.get("sizeClass")) for row in rows if normalize(row.get("sizeClass")))
    roofs = collections.Counter(normalize(row.get("roofFamily")) for row in rows if normalize(row.get("roofFamily")))
    palettes = collections.Counter(normalize(row.get("paletteProfile")) for row in rows if normalize(row.get("paletteProfile")))
    details = collections.Counter(normalize(row.get("detailDensity")) for row in rows if normalize(row.get("detailDensity")))
    primary_themes = collections.Counter()
    secondary_themes = collections.Counter()
    floors: List[int] = []

    for row in rows:
        learned_primary = normalize(row.get("learnedPrimaryTheme"))
        style_primary = normalize(row.get("stylePrimaryTheme"))
        learned_secondary = normalize(row.get("learnedSecondaryTheme"))
        style_secondary = normalize(row.get("styleSecondaryTheme"))

        primary = learned_primary or style_primary
        secondary = learned_secondary or style_secondary
        if primary:
            primary_themes[primary] += 1
        if secondary and secondary != primary:
            secondary_themes[secondary] += 1

        try:
            floors.append(int(row.get("floors", 1)))
        except (TypeError, ValueError):
            floors.append(1)

    archetype, archetype_hits = most_common(archetypes)
    palette, palette_hits = most_common(palettes)
    roof, roof_hits = most_common(roofs)
    size_class, size_hits = most_common(size_classes)
    detail, detail_hits = most_common(details)
    primary_theme, _ = most_common(primary_themes)
    secondary_theme, _ = most_common(secondary_themes)
    mean_floors = max(1, int(round(sum(floors) / max(1, len(floors)))))

    purity_terms = [
        safe_ratio(archetype_hits, samples),
        safe_ratio(palette_hits, samples),
        safe_ratio(roof_hits, samples),
        safe_ratio(size_hits, samples),
        safe_ratio(detail_hits, samples),
    ]
    purity = sum(purity_terms) / len(purity_terms)
    confidence = min(0.95, 0.35 + purity * 0.40 + min(1.0, samples / 12.0) * 0.20)

    return GroupSummary(
        samples=samples,
        archetype=archetype,
        size_class=size_class,
        floors=mean_floors,
        roof_family=roof,
        palette_profile=palette,
        detail_density=detail,
        primary_theme=primary_theme,
        secondary_theme=secondary_theme,
        confidence=round(confidence, 4),
    )


def most_common(counter: collections.Counter[str]) -> tuple[str, int]:
    if not counter:
        return "", 0
    return counter.most_common(1)[0]


def safe_ratio(numerator: int, denominator: int) -> float:
    if denominator <= 0:
        return 0.0
    return numerator / float(denominator)


def encode_summary(summary: GroupSummary) -> dict:
    return {
        "archetype": summary.archetype,
        "sizeClass": summary.size_class,
        "floors": summary.floors,
        "roofFamily": summary.roof_family,
        "paletteProfile": summary.palette_profile,
        "detailDensity": summary.detail_density,
        "primaryTheme": summary.primary_theme,
        "secondaryTheme": summary.secondary_theme,
        "confidence": summary.confidence,
        "samples": summary.samples,
    }


def top_named_counts(counter: collections.Counter[str], limit: int) -> List[dict]:
    out: List[dict] = []
    for name, count in counter.most_common(limit):
        if not name:
            continue
        out.append({"name": name, "count": count})
    return out


def int_value(row: dict, key: str, fallback: int = 0) -> int:
    try:
        return int(row.get(key, fallback))
    except (TypeError, ValueError):
        return fallback


def clamp(value: float, minimum: float, maximum: float) -> float:
    return max(minimum, min(maximum, value))


def generation_features(row: dict) -> List[float] | None:
    selection_width = int_value(row, "selMaxX") - int_value(row, "selMinX") + 1
    selection_depth = int_value(row, "selMaxZ") - int_value(row, "selMinZ") + 1
    preview_width = int_value(row, "bodyWidth")
    preview_depth = int_value(row, "bodyDepth")
    if preview_width <= 0:
        preview_width = int_value(row, "previewMaxX") - int_value(row, "previewMinX") + 1
    if preview_depth <= 0:
        preview_depth = int_value(row, "previewMaxZ") - int_value(row, "previewMinZ") + 1
    if min(selection_width, selection_depth, preview_width, preview_depth) <= 0:
        return None

    floors = max(1, int_value(row, "actualFloors", int_value(row, "floors", 1)))
    max_roof_layers = max(1, min(preview_width, preview_depth) // 2)
    roof_layers = int_value(row, "roofLayers")
    if roof_layers <= 0:
        requested = {"low": 2, "gable": 3, "steep": 4}.get(normalize(row.get("roofFamily")), 3)
        roof_layers = min(max_roof_layers, requested)

    width_fill = clamp(preview_width / float(selection_width), 0.0, 1.25)
    depth_fill = clamp(preview_depth / float(selection_depth), 0.0, 1.25)
    return [
        width_fill,
        depth_fill,
        clamp(width_fill * depth_fill, 0.0, 1.5),
        min(preview_width, preview_depth) / float(max(preview_width, preview_depth)),
        float(clamp(float(floors), 1.0, 4.0)),
        clamp(roof_layers / float(max_roof_layers), 0.0, 1.0),
    ]


def sigmoid(value: float) -> float:
    if value >= 0.0:
        exp_value = math.exp(-value)
        return 1.0 / (1.0 + exp_value)
    exp_value = math.exp(value)
    return exp_value / (1.0 + exp_value)


def dot(left: Sequence[float], right: Sequence[float]) -> float:
    return sum(a * b for a, b in zip(left, right))


def build_generation_preference(preview_rows: List[dict]) -> dict:
    samples: List[tuple[List[float], int]] = []
    for row in preview_rows:
        outcome = normalize(row.get("outcome"))
        if outcome not in {"accepted", "rejected", "rerolled"}:
            continue
        features = generation_features(row)
        if features is not None:
            samples.append((features, 1 if outcome == "accepted" else 0))

    positives = sum(label for _, label in samples)
    negatives = len(samples) - positives
    enabled = len(samples) >= MIN_GENERATION_SAMPLES and positives >= 2 and negatives >= 2
    means = [0.0] * len(GENERATION_FEATURES)
    scales = [1.0] * len(GENERATION_FEATURES)
    weights = [0.0] * len(GENERATION_FEATURES)
    bias = 0.0
    balanced_accuracy = 0.0
    log_loss = 0.0

    if samples:
        for feature_index in range(len(GENERATION_FEATURES)):
            values = [features[feature_index] for features, _ in samples]
            means[feature_index] = sum(values) / len(values)
            variance = sum((value - means[feature_index]) ** 2 for value in values) / len(values)
            scales[feature_index] = max(0.05, math.sqrt(variance))

    if enabled:
        normalized_samples = [
            ([(value - means[i]) / scales[i] for i, value in enumerate(features)], label)
            for features, label in samples
        ]
        bias = math.log((positives + 1.0) / (negatives + 1.0))
        positive_weight = len(samples) / (2.0 * positives)
        negative_weight = len(samples) / (2.0 * negatives)

        for step in range(900):
            gradient = [0.0] * len(weights)
            bias_gradient = 0.0
            total_sample_weight = 0.0
            for features, label in normalized_samples:
                sample_weight = positive_weight if label == 1 else negative_weight
                error = sigmoid(bias + dot(weights, features)) - label
                bias_gradient += error * sample_weight
                for feature_index, value in enumerate(features):
                    gradient[feature_index] += error * value * sample_weight
                total_sample_weight += sample_weight

            learning_rate = 0.12 / (1.0 + step / 450.0)
            bias -= learning_rate * bias_gradient / max(1.0, total_sample_weight)
            for feature_index in range(len(weights)):
                data_gradient = gradient[feature_index] / max(1.0, total_sample_weight)
                weights[feature_index] -= learning_rate * (data_gradient + 0.04 * weights[feature_index])

        true_positive = true_negative = 0
        loss_total = 0.0
        for features, label in normalized_samples:
            probability = clamp(sigmoid(bias + dot(weights, features)), 1.0e-8, 1.0 - 1.0e-8)
            prediction = 1 if probability >= 0.5 else 0
            true_positive += 1 if label == 1 and prediction == 1 else 0
            true_negative += 1 if label == 0 and prediction == 0 else 0
            loss_total += -(label * math.log(probability) + (1 - label) * math.log(1.0 - probability))
        balanced_accuracy = 0.5 * (true_positive / positives + true_negative / negatives)
        log_loss = loss_total / len(normalized_samples)

    return {
        "enabled": enabled,
        "minimumSamples": MIN_GENERATION_SAMPLES,
        "samples": len(samples),
        "positiveSamples": positives,
        "negativeSamples": negatives,
        "featureNames": list(GENERATION_FEATURES),
        "means": [round(value, 8) for value in means],
        "scales": [round(value, 8) for value in scales],
        "weights": [round(value, 8) for value in weights],
        "bias": round(bias, 8),
        "balancedAccuracy": round(balanced_accuracy, 4),
        "logLoss": round(log_loss, 6),
    }


def build_zone_priors(intent_rows: List[dict]) -> Dict[str, dict]:
    grouped: Dict[str, List[dict]] = collections.defaultdict(list)
    for row in intent_rows:
        zone = normalize(row.get("zoneType"))
        if zone:
            grouped[zone].append(row)

    priors: Dict[str, dict] = {}
    for zone, rows in grouped.items():
        summary = build_group_summary(rows)
        if summary is not None:
            priors[zone] = encode_summary(summary)
    return priors


def build_theme_priors(intent_rows: List[dict]) -> Dict[str, dict]:
    grouped: Dict[str, List[dict]] = collections.defaultdict(list)
    for row in intent_rows:
        learned = normalize(row.get("learnedPrimaryTheme"))
        style = normalize(row.get("stylePrimaryTheme"))
        theme = learned or style
        if theme:
            grouped[theme].append(row)

    priors: Dict[str, dict] = {}
    for theme, rows in grouped.items():
        summary = build_group_summary(rows)
        if summary is not None:
            priors[theme] = encode_summary(summary)
    return priors


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train Bladelow offline priors from JSONL datasets.")
    parser.add_argument(
        "--ml-dir",
        default="config/bladelow/ml",
        help="Directory containing placement_style_events.jsonl and related datasets.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Optional output path. Defaults to <ml-dir>/offline_model.json",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    ml_dir = Path(args.ml_dir)
    output_path = Path(args.output) if args.output else ml_dir / "offline_model.json"
    ml_dir.mkdir(parents=True, exist_ok=True)

    placement_rows = read_jsonl(ml_dir / "placement_style_events.jsonl")
    environment_rows = read_jsonl(ml_dir / "environment_observations.jsonl")
    intent_rows = read_jsonl(ml_dir / "build_intent_examples.jsonl")
    style_example_rows = read_jsonl(ml_dir / "style_examples.jsonl")
    preview_feedback_rows = read_jsonl(ml_dir / "preview_feedback.jsonl")

    theme_counts = weighted_theme_counts(environment_rows, style_example_rows)
    palette_counts = collections.Counter(
        normalize(row.get("paletteProfile"))
        for row in intent_rows
        if normalize(row.get("paletteProfile"))
    )

    model = {
        "version": 2,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "sampleCounts": {
            "placementEvents": len(placement_rows),
            "environmentObservations": len(environment_rows),
            "buildIntentExamples": len(intent_rows),
            "styleExamples": len(style_example_rows),
            "previewFeedback": len(preview_feedback_rows),
            "styleReferenceImages": count_images(ml_dir / "style_refs"),
        },
        "topThemes": top_named_counts(theme_counts, 6),
        "topPalettes": top_named_counts(palette_counts, 6),
        "zonePriors": build_zone_priors(intent_rows),
        "themePriors": build_theme_priors(intent_rows),
        "generationPreference": build_generation_preference(preview_feedback_rows),
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        json.dump(model, handle, indent=2, sort_keys=True)
        handle.write("\n")

    print(f"trained offline model -> {output_path}")
    print(
        "samples:",
        f"placements={len(placement_rows)}",
        f"env={len(environment_rows)}",
        f"intent={len(intent_rows)}",
        f"style_examples={len(style_example_rows)}",
        f"preview_feedback={len(preview_feedback_rows)}",
    )
    if model["topThemes"]:
        print("top themes:", ", ".join(f"{entry['name']}({entry['count']})" for entry in model["topThemes"]))
    if model["zonePriors"]:
        print("zone priors:", ", ".join(sorted(model["zonePriors"].keys())))
    generation = model["generationPreference"]
    print(
        "generation preference:",
        "trained" if generation["enabled"] else "waiting for balanced feedback",
        f"samples={generation['samples']}",
        f"accepted={generation['positiveSamples']}",
        f"negative={generation['negativeSamples']}",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
